filme/urls.py
#Quando for criar uma pagina você tem que levar esses três pontos em mente

# url - view - templete
from django.urls import path, reverse_lazy
from .views import Homepage, Homefilmes, Detalhesfilmes, Pesquisa, Editarperfil, Criarconta
from django.contrib.auth import views as auth_views #Como uma página de login é padrão no django já temos uma view pronta.

app_name = "filme"#nome da app que vai ser direcionada pra ulr principal do projeto

urlpatterns = [
    path('', Homepage.as_view(), name="homepage"), #name serve para direncionar os link e identificar
    path('filmes/', Homefilmes.as_view(), name="homefilmes"), # sem os () por padrão o dj passa o request
    path('filmes/<int:pk>', Detalhesfilmes.as_view(), name="detalhesfilmes"),#pk = primery_key, pega os id do modelo filme
    path('pesquisa/', Pesquisa.as_view(), name='pesquisa'),
    path('login/', auth_views.LoginView.as_view(template_name = 'login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('editarperfil/<int:pk>', Editarperfil.as_view(), name="editarperfil"),
    path('criar/', Criarconta.as_view(), name="criarconta"),
    path('mudarsenha/', auth_views.PasswordChangeView.as_view(template_name='editarperfil.html', success_url="reverse_lazy('filme:homefilmes)"), name='mudarsenha'),
]

hashflix/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('filme.urls', namespace="filme"))#namespace coloca o nome do app_name no ulr do nosso app, e inclui todas as urls do nosso site
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

filme/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser #O django por padrão já tem um modelo de usuario, nesse caso quando vc quer personalizar um usuario vc tem que dizer pro django que o modelo de usuario nao vai ser do padrao django


# Create your models here.

#criar um filme
#sub class vai receber no seu parametro seu modelo padrão é uma sub classe do models.Model
lista_categorias = (
    #Na tupla tem que armazenar duas informações uma que vai armazenar no banco de dados(armazenar.db, aparecer_pro_usuario)
    ("ANALISES", "Análises"),
    ("PROGRAMACAO", "Programação"),
    ("APRESENTACAO", "Apresentação"),
    ("OUTROS", "Outros")
)

class Filme(models.Model):
    titulo = models.CharField(max_length=100)
    thumb = models.ImageField(upload_to='thumb_filmes')
    descricao = models.TextField(max_length=1000)
    categoria = models.CharField(max_length=15, choices=lista_categorias)#No chafield vc vai passar dois parametros o máximo de caracteres que vai ocupar no seu bd, e passar a lista por meio do parametro choices
    vizualizacoes = models.IntegerField(default=0) #default um valor padrão
    data_criacao = models.DateTimeField(default=timezone.now)
    #Ela diz qual é o formato de string de um objeto nessa class, como você quer que ele seja exibido.
    def __str__(self):
        return self.titulo

#criar um usuario

#criar os espisodios
#fazendo uma referencia!

class Episodio(models.Model):
    #primeiro campo chave estrangeira pra fazer a referencia!!!!
    #Foreignkey("nome da tabela, releatade_name, server para add um campo especifico na tabela que vai ser acessado atraves do object. no html, on_delete = models.cascade serve para deletar todos epissdios relacionados ao filme deletado")
    filme = models.ForeignKey("Filme", related_name="episodios", on_delete=models.CASCADE)#ELE DIZ QUE ESSE ITEM FILME ESTÁ RELACIONADO COM A OUTRA TABELA, ALEM DISSO UM FILME PODE TER VARIOS EPISODIO MAIS VARIOS FILMES NÃO PODE FAZER REFERNCIA AO MESMO ESPISODIO. SE QUER QUE ISSO ACONTEÇA USA O models.ManyToManyField()
    titulo = models.CharField(max_length=100)
    video = models.URLField()#Fala que é um link
    def __str__(self):
        return self.titulo
    
class Usuario(AbstractUser):#voce normalmente iria colocar os campos do usuario mas o class abstractuser ela já vem com esses campos criados.
    filmes_vistos = models.ManyToManyField('Filme')

filme/forms.py
#criar nossos formularios personalizados
from django.contrib.auth.forms import UserCreationForm

from .models import Usuario
from django import forms #serve para add um campo de formulario

class CriarContaForm(UserCreationForm):
    email = forms.EmailField()# se vc n passa nada entre os parenteses esse campo ele é obrigatório. opcional é required = False
    #Nesse usercreationform vc precisa dizer pra ele dentro dessa class voce tem que definir uma outra class chamada meta:

    class Meta:#diz pra ele quem é o modelo que ele tem que utilizar como referencia.
        model = Usuario
        fields = ('username', 'email', 'password1', 'password2')#fields é uma tupla onde vai exebir os campos dos formularios, que tem esse nome padrão da class usercreationform

class FormDaHomePage(forms.Form):#estmaos criando um formulário padrão do django então não precisamos da usercreationform.
    email = forms.EmailField(label=False)

filme/views.py
from django.shortcuts import render, redirect, reverse
from .models import Filme, Usuario
from django.views.generic import TemplateView, ListView, DetailView, FormView, UpdateView #uma class que verifica o form
from .forms import CriarContaForm, FormDaHomePage
from django.contrib.auth.mixins import LoginRequiredMixin #Importa uma class que é responsavel para bloquear as páginas e permitir o acesso só pra quem estiver logado no site, detalhe importante é que essa class tem que ser passada como o 1 parametro exemplo: class Homepage(LoginRequiredMixin, TemplateView)
# Create your views here.
# EXPLICAÇÃO DO REQUEST

# Quando você entra em um site, você faz uma requisição, a qual pode ser duas formas, get e post, quando você entra em um site você tá fazendo uma requisição do tipo get, uma requisição do tipo post é quando você preenche um formulário e envia ele.

#E ele é obrigatório porque ele tá dizendo pra essa view se ele é uma requisição do tipo get ou post

# def homepage(request):
#     return render(request, "homepage.html")# o render por padrao recebe o request e  o arquivo template.

class Homepage(FormView):
    template_name = "homepage.html"
    form_class = FormDaHomePage

    def get_success_url(self):
        email = self.request.POST.get('email')
        usuarios = Usuario.objects.filter(email=email)
        if usuarios:
            return reverse('filme:login')
        else:
            return reverse('flime:criarconta')

    def get(self, request, *args, **kwargs): # nosso user fica dentro do request então vai ser request.user.is_authenticated
        if request.user.is_authenticated : #verifica se o usuario está logado
            return redirect('filme:homefilmes')#Não usaremos o render pq ele n iria funcionar bem com isso
        else:
        #Caso o usuario não estiver logado redireciona para url final que é a minha homepage
            return super().get(request, *args, **kwargs)

# def homefilmes(request):
#     context = {}
#     listas_filmes = Filme.objects.all() #pega todos os objetos dentro da sua class .all()
#     context['listas_filmes'] = listas_filmes
#     return render(request, "homefilmes.html", context)

#você passar as informações do banco de dados para a parte front, é um context q é básicamente um dicionario no python

#TRANSFORMANDO NOSSA FUNÇÃO EM UMA CLASS BASED VÍDEO 21

# A lista view pede duas variavel o nome do template e o seu modelo.

class Homefilmes(LoginRequiredMixin, ListView):
    template_name = "homefilmes.html"
    model = Filme #object_list -> todos os itens do modelo
    #Ele oferece o context e retorna com o nome de chave de object_list
   
#Criando viwes pro nossos filmes
#Como não é um template nois vamos exibir os detlhes desse item com o dateils view

class Detalhesfilmes(LoginRequiredMixin, DetailView):
    template_name = "detalhesfilmes.html"
    model = Filme
    #  retorna com o nome object -> 1 item do modelo
    def get(self, request, *args, **kwargs): #a gente vai retornar uma super porque estamos editando uma função de class que já existe
        #contabilizou a vizualização
        filme = self.get_object()
        filme.vizualizacoes += 1
        filme.save() # salvou no banco de dados
        usuario = request.user
        usuario.filmes_vistos.add(filme)
        return super().get(request, *args, **kwargs) #redireciona o usuario pra url final



    def get_context_data(self, **kwargs):
        context = super(Detalhesfilmes, self).get_context_data(**kwargs)
        filmes_relacionados = Filme.objects.filter(categoria= self.get_object().categoria)[0:3]

        context['filmes_relacionados'] = filmes_relacionados

        return context
    
class Pesquisa(LoginRequiredMixin, ListView):
    template_name = 'pesquisa.html'
    model = Filme

    def get_queryset(self): #função pronta serve para pegar os parametros passado na url!
        termo_pesquisa = self.request.GET.get('query') #qual a pesquisa que ele passou no input, self.request.GET eu quero que ele execute quando ele usar essa requisição method get. o GET é o tipo da requisição e o .get é oq eu quero pegar como parametro
        #E dentro do get('nome do input') vai passar o name do seu input
        if termo_pesquisa: # Voce pode colocar no local de Filme self.model  pq ele vai estar se referindo ao modelo da nossa class model = Filme
            object_list = Filme.objects.filter(titulo__icontains = termo_pesquisa)#aqui eu to passando um filtro pro meu object_list, o parametro icontains serve pra dizer cotem a nossa pesquisa. nesse caso é o titulo que a gente passou.
            return object_list
        else:
            return None

class Editarperfil(LoginRequiredMixin, UpdateView):
    template_name = 'editarperfil.html'
    model = Usuario
    fields = ['first_name', 'last_name', 'email']# a Updateview pede o fields e o modelo, esse first last, são tudo do nosso abstract user da class padrão, então por isso que os nomes estão assim desse jeito
    def get_success_url(self):
        return reverse('filme:homefilmes')


class Criarconta (FormView):
    template_name = 'criar.html'
    form_class = CriarContaForm

    #quando voce criar um form view vc tem que tratar ou editar 2 def

    def form_valid(self, form):#verifica se o formulario é valido
        form.save()#salva o usuario e add um item no banco de dados
        return super().form_valid(form)
    

    def get_success_url(self):#Te direciona caso a conta for aprovada ela te direciona através de um link. ELA ESPERA UM URL COMO RESPOSTA por isso n usamos o redirect.
        return reverse('filme:login')

filme/templates/criar.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}  

{% block titulo %}
    Criar Conta
{% endblock %}
{% block head %}
<style>
    #id_username {
        background-color:white;
        color:black;
        border:solid 1px black;
        border-radius:10px;
        padding:10px;
        width:100%
    }
    #id_email {
        background-color:white;
        color:black;
        border:solid 1px black;
        border-radius:10px;
        padding:10px;
        width:100%
    }
    #id_password1 {
        background-color:white;
        color:black;
        border:solid 1px black;
        border-radius:10px;
        padding:10px;
        width:100%
    }
    #id_password2 {
        background-color:white;
        color:black;
        border:solid 1px black;
        border-radius:10px;
        padding:10px;
        width:100%
    }
</style>
{% endblock  %}
{% block content %}
<header class="min-h-screen bg-black bg-opacity-75 showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('{% static 'images/fundo-netflix.jpg'%}');">
    <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
        <form method="post">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4 text-2xl">Crie uma conta para continuar</legend>
                {{form|crispy}}
            </fieldset>
            <button class="bg-red-600 py-1 px-3 text-white w-full md:text-lg rounded-md" type="submit">Criar Conta</button>
        </form>

    </div>
</header>

<footer class=" px-5 py-10 ">
    <ul class="flex justify-between items-center">
        
        <li>&copy; 2021</li>
        <li> Feito com Python (Django)</li>
        <li>Hashtag</li>
    </ul>
</footer>
{% endblock %}

filme/templates/detalhesfilmes.html
{% extends "base.html" %}


{% block titulo %}
    HomeFilmes Hashflix
{% endblock %}

{% block content %}
    

<main class='bg-primary_black min-h-screen w-full'>
    <section class="h-screen relative bg-no-repeat pb-8 pl-6 flex  items-end bg-cover" style="background-image: url('{{object.thumb.url}}');">
        <div>
            <h2 class="text-6xl font-semibold text-white my-4">
                {{object.titulo}}
            </h2>
            <p class=" w-11/12 md:w-5/12 font-medium text-white my-4">
                {{object.descricao|slice:"100"}}
            </p>
            <div class="flex my-4">
                <a href="{{object.episodios.first.video}}">
                    <button class="flex items-center bg-white py-2 px-5 rounded-md" style='color:black;'>
                        <ion-icon name="play" class="text-2xl"></ion-icon>
                        <span class="ml-3 font-medium">
                            Play
                        </span>
                    </button>
                </a>
            </div>
        </div>
    </section> 
    <section class='bg-primary_black flex justify-center py-10'>
        <div class="p-8 w-10/12 relative" >
            <h2 class="text-gray-200 text-3xl font-medium">
                Descrição
            </h2>
            <div class="flex justify-left  items-center min-w-full  movie_lis">
                <p class="text-gray-100 text-lg">
                    {{object.descricao}}
                    <br>
                    Visualizações: {{object.vizualizacoes}}
                </p>
            </div>

            <div style='margin-top:2rem;margin-bottom:2rem;'>
                <h2 class="text-gray-200 text-3xl font-medium">
                    Episódios

                </h2>
                {% for episodios in object.episodios.all %}
                    <h3 class='text-lg'>
                        <a href="{{episodios.video}}">
                           Episodio {{forloop.counter}}: {{episodios}}
                        </a>
                    </h3>
                 {% endfor %}   
            </div>
        </div>
    </section>

    <section class='bg-primary_black flex justify-center py-10'>
        <div class="p-8 w-10/12 relative" >
            <h2 class="text-gray-200 text-2xl font-medium">
                Relacionados
            </h2>
            <div class="flex flex-wrap items-center min-w-full movie_lis">
                {% for filme in filmes_relacionados %}
                <div class="m-4 bg-blue-500 overflow-hidden flex-shrink-0 rounded-md cursor-pointer h-64 w-96">
                    <a href="{%url 'filme:detalhesfilmes' filme.pk %}">
                            <img src="{{filme.thumb.url}}" class="object-cover w-full h-full " alt="">
                    </a>
                    </div>
                {%endfor%}
            </div>
        </div>
    </section>
    
</main>
{% endblock%}

filme/templates/editarperfil.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block titulo %}
    Editar Perfil
{% endblock %}

{% block head %}
<style>
    #id_last_name {
        background-color:white;
        color:black;
        border:solid 1px black;
        border-radius:10px;
        padding:10px;
        width:100%
    }
    #id_email {
        background-color:white;
        color:black;
        border:solid 1px black;
        border-radius:10px;
        padding:10px;
        width:100%
    }
    #id_first_name {
        background-color:white;
        color:black;
        border:solid 1px black;
        border-radius:10px;
        padding:10px;
        width:100%
    }
    #id_old_password{
        background-color:white;
        color:black;
        border:solid 1px black;
        border-radius:10px;
        padding:10px;
        width:100%
    }
    #id_new_password1{
        background-color:white;
        color:black;
        border:solid 1px black;
        border-radius:10px;
        padding:10px;
        width:100%
    }
    #id_new_password2{
        background-color:white;
        color:black;
        border:solid 1px black;
        border-radius:10px;
        padding:10px;
        width:100%
    }
</style>
{% endblock  %}

{% block content %}
  

<header class="min-h-screen bg-black bg-opacity-75 showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('{%static 'images/fundo-netflix.jpg'%}');">
    <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
        <h2>Usuario</h2>

        <form method="post">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Edite os campos abaixo para editar seu perfil</legend>
                {{form|crispy}}
            </fieldset>
            <button class="bg-red-600 py-1 px-3 text-white md:text-lg rounded-md" type="submit">Editar Perfil</button>
        </form>
        <small><a href="{%url 'filme:mudarsenha'%}">Quer mudar sua senha?</a></small>
    </div>
</header>

<footer class=" px-5 py-10 ">
    <ul class="flex justify-between items-center">
        
        <li>&copy; 2021</li>
        <li> Feito com Python (Django)</li>
        <li>Hashtag</li>
    </ul>
</footer>



{% endblock %}

filme/templates/homefilmes.html
{% extends "base.html" %}
{% load static %}

{% block titulo %}
    HomeFilmes Hashflix
{% endblock %}

{% block head %}
<style>
    $itemGrow: 1.2;
$duration: 250ms;

html {
  scroll-behavior: smooth;
}

body {
  margin: 0;
  background-color: #000;
}

h1 {
  font-family: Arial;
  color: red;
  text-align: center;
}

.wrapper {
  display: grid;
  grid-template-columns: repeat(3,100%);
  overflow:hidden;
  scroll-behavior: smooth;

  section {
    width: 100%;
    position: relative;
    margin: 20px 0;

    .item {
      padding: 0 2px;
      transition: $duration all;

      &:hover {
        margin: 0 20px;
        transform: scale(1.2);
      }

    }
    
    a {
      /* position: absolute; */
      color: #fff;
      text-decoration: none;
      font-size: 6em;
      background:rgb(0,0,0);
      text-align: center;
      z-index: 1;

    }

    &>a:first-child {
      position: absolute;
        left:0;
        background: linear-gradient(-90deg, rgba(0,0,0,0) 0%, rgba(0,0,0,1) 100%);
      }
      &>a:last-child {
        position: absolute;
        right: 0;
        background: linear-gradient(90deg, rgba(0,0,0,0) 0%, rgba(0,0,0,1) 100%);
      }
  }
}

// Remove the arrow for Mobile
@media only screen and (max-width: 600px) {
  a.arrow__btn {
    display:none;
  }
}
</style>
{% endblock %}

{% block content %}

<main class='bg-primary_black min-h-screen w-full'>
    <section class="h-screen relative bg-no-repeat pb-8 pl-6 flex items-end bg-cover" style="background-image: url('{{lista_destaque.thumb.url}}');">
        <div>
            <h2 class="text-6xl font-semibold text-white my-4">
                {{lista_destaque.titulo}}
            </h2>
            <p class=" w-11/12 md:w-5/12 font-medium text-white my-4">
                {{lista_destaque.descricao}}
            </p>
            <div class="flex my-4">
                <a href="{%url 'filme:detalhesfilmes' lista_destaque.pk%}">
                    <button class="flex items-center bg-white py-2 px-5 rounded-md" style='color:black;'>
                        <ion-icon name="play" class="text-2xl"></ion-icon>
                        <span class="ml-3 font-medium " >
                            Play
                        </span>
                    </button>
                </a>
            </div>
        </div>
    </section> 


    <section class='bg-primary_black flex justify-center py-10'>
        <div class="p-8 w-10/12 relative" >
            <h2 class="text-gray-200 text-2xl font-medium">
                Novo
            </h2>
            <div class="wrapper">
              <section id="section1" class="flex flex-nowrap items-center justify-center space-x-8">
                <a href="#section2" class="arrow__btn text-6xl page">‹</a>
                {% for filme in lista_filmes_recentes %}
                    {% if forloop.counter < 5 %}
                  <div class="item h-64 w-1/4 m-4">
                        <a href="{%url 'filme:detalhesfilmes' filme.pk%}">
                            <img src="{{filme.thumb.url}}" class="rounded-md w-full h-full object-cover">
                        </a>
                  </div>
                  {% endif %}
                {% endfor %}
                    <a href="#section2" class="arrow__btn text-6xl">›</a>
              </section>
              {% if lista_filmes_recentes|length > 4 %}
                  <section id="section2" class="flex flex-nowrap items-center justify-center">
                    <a href="#section1" class="arrow__btn text-6xl">‹</a>
                    {% for filme in lista_filmes_recentes %}
                        {% if forloop.counter > 4 %}
                      <div class="item h-64 w-1/4 m-4">
                            <a href="{%url 'filme:detalhesfilmes' filme.pk%}">
                                <img src="{{filme.thumb.url}}" class="rounded-md w-full h-full object-cover">
                            </a>
                      </div>
                      {% endif %}
                    {% endfor %}
                    <a href="#section1" class="arrow__btn text-6xl">›</a>
                  </section>
                  {% endif %}
            </div>


        </div>
    </section>

    <section class='bg-primary_black flex justify-center py-10'>
        <div class="p-8 w-10/12 relative" >
            <h2 class="text-gray-200 text-2xl font-medium">
                EM ALTA NA HASHFLIX!
            </h2>
            <div class="wrapper">
              <section id="section3" class="flex flex-nowrap items-center justify-center space-x-8">
                <a href="#section4" class="arrow__btn text-6xl page">‹</a>
                {% for filme in filmes_populares %}
                    {% if forloop.counter < 5 %}
                  <div class="item h-64 w-1/4 m-4">
                        <a href="{%url 'filme:detalhesfilmes' filme.pk%}">
                            <img src="{{filme.thumb.url}}" class="rounded-md w-full h-full object-cover">
                        </a>
                  </div>
                  {% endif %}
                {% endfor %}
                    <a href="#section4" class="arrow__btn text-6xl">›</a>
              </section>
              {% if filmes_populares|length > 4 %}
                  <section id="section4" class="flex flex-nowrap items-center justify-center">
                    <a href="#section3" class="arrow__btn text-6xl">‹</a>
                    {% for filme in filmes_populares %}
                        {% if forloop.counter > 4 %}
                      <div class="item h-64 w-1/4 m-4">
                            <a href="{%url 'filme:detalhesfilmes' filme.pk%}">
                                <img src="{{filme.thumb.url}}" class="rounded-md w-full h-full object-cover">
                            </a>
                      </div>
                      {% endif %}
                    {% endfor %}
                    <a href="#section3" class="arrow__btn text-6xl">›</a>
                  </section>
                  {% endif %}
            </div>


        </div>
    </section>

    <section class='bg-primary_black flex justify-center py-10'>
      <div class="p-8 w-10/12 relative" >
          <h2 class="text-gray-200 text-2xl font-medium">
              Filmes Assistidos
          </h2>
          <div class="wrapper">
            <section id="section1vistos" class="flex flex-nowrap items-center justify-center space-x-8">
              <a href="#section2vistos" class="arrow__btn text-6xl page">‹</a>
              {% for filme in request.user.filmes_vistos.all  %}
                  {% if forloop.counter < 5 %}
                <div class="item h-64 w-1/4 m-4">
                      <a href="{%url 'filme:detalhesfilmes' filme.pk%}">
                          <img src="{{filme.thumb.url}}" class="rounded-md w-full h-full object-cover">
                      </a>
                </div>
                {% endif %}
              {% endfor %}
                  <a href="#section2vistos" class="arrow__btn text-6xl">›</a>
            </section>
            {% if lista_filmes_recentes|length > 4 %}
                <section id="section2vistos" class="flex flex-nowrap items-center justify-center">
                  <a href="#section1vistos" class="arrow__btn text-6xl">‹</a>
                  {% for filme in request.user.filmes_vistos.all %}
                      {% if forloop.counter > 4 %}
                    <div class="item h-64 w-1/4 m-4">
                          <a href="{%url 'filme:detalhesfilmes' filme.pk%}">
                              <img src="{{filme.thumb.url}}" class="rounded-md w-full h-full object-cover">
                          </a>
                    </div>
                    {% endif %}
                  {% endfor %}
                  <a href="#section1vistos" class="arrow__btn text-6xl">›</a>
                </section>
                {% endif %}
          </div>


      </div>
  </section>_
</main>
{% endblock%}

filme/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block titulo %}
    Login
{% endblock %}

{% block head %}
<style>
    #id_username {
        background-color:white;
        color:black;
        border:solid 1px black;
        border-radius:10px;
        padding:10px;
        width:100%
    }
    #id_email {
        background-color:white;
        color:black;
        border:solid 1px black;
        border-radius:10px;
        padding:10px;
        width:100%
    }
    #id_password {
        background-color:white;
        color:black;
        border:solid 1px black;
        border-radius:10px;
        padding:10px;
        width:100%
    }
</style>
{% endblock  %}
    
{% block content %}
   
<header class="min-h-screen bg-black bg-opacity-75 showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('{% static 'images/fundo-netflix.jpg'%}');">
    <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
        <form method="post">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4 text-2xl" style="text-decoration:underline;">Faça Login para continuar</legend>
                {{form|crispy}}<!--A class view do login já passa pro seu template que vc coloca nela esse form, esse crispy é para estilo do bootsstrap ok?-->
            </fieldset>
            <button class="bg-red-600 py-1 my-2 px-3 w-full text-white md:text-lg rounded-md" type="submit">Fazer Login</button>
        </form>
        <small>
            Não tem uma conta ainda? <p><a href="{%url 'filme:criarconta'%}">Clique aqui para criar uma conta</a></p>
        </small>
    </div>
</header>

<footer class=" px-5 py-10 ">
    <ul class="flex justify-between items-center">
        
        <li>&copy; 2021</li>
        <li> Feito com Python (Django)</li>
        <li>Hashtag</li>
    </ul>
</footer>
{% endblock %}

filme/templates/logout.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
    Logout
{% endblock %}

{% block content %}
<header class="min-h-screen bg-black bg-opacity-75 showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('{%static 'images/fundo-netflix.jpg'%}');">
    <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
        <h2>Você saiu da sua conta</h2>
        <div class="flex flex-nowrap justify-center space-x-5 p-5">
        <a href="{%url 'filme:login'%}"><button class="bg-red-600 py-1 px-3 text-white md:text-lg rounded-md">Fazer Login</button></a>
        <a href="{%url 'filme:criarconta'%}"><button class="bg-red-600 py-1 px-3 text-white md:text-lg rounded-md">Criar uma Conta</button></a>
        </div>
    </div>
</header>

<footer class=" px-5 py-10 ">
    <ul class="flex justify-between items-center">
        
        <li>&copy; 2021</li>
        <li> Feito com Python (Django)</li>
        <li>Hashtag</li>
    </ul>
</footer>
{% endblock %}

filme/templates/pesquisa.html
{% extends "base.html" %}

{% block titulo %}
    Pesquisa filmes
{% endblock  %}

{% block content %}
    
<main class='bg-primary_black min-h-screen w-full'>
    <section class='bg-primary_black  min-h-screen flex justify-center py-10'>
        <div class="p-8 w-10/12 relative" >
            <h2 class="text-gray-200 text-2xl font-medium">
                Resultados da Busca
            </h2>
            <div class="flex flex-wrap items-center min-w-full movie_lis">
                {% for filme  in object_list %}
                <div class="m-4 bg-blue-500 overflow-hidden flex-shrink-0 rounded-md cursor-pointer h-64 w-96">
                    <a href="{%url 'filme:detalhesfilmes' filme.pk %}">
                            <img src="{{filme.thumb.url}}" class="object-cover w-full h-full " alt="filmes">
                    </a>
                    </div>
                {% endfor %}
            </div>


        </div>
    </section>
</main>
{% endblock  %}