filme/urls.py
#Quando for criar uma pagina você tem que levar esses três pontos em mente

# url - view - templete
from django.urls import path, reverse_lazy
from .views import Homepage, Homefilmes, Detalhesfilmes, Pesquisa, Editarperfil, Criarconta
from django.contrib.auth import views as auth_views #Como uma página de login é padrão no django já temos uma view pronta.

app_name = "filme"#nome da app que vai ser direcionada pra ulr principal do projeto

urlpatterns = [
    path('', Homepage.as_view(), name="homepage"), #name serve para direncionar os link e identificar
    path('filmes/', Homefilmes.as_view(), name="homefilmes"), # sem os () por padrão o dj passa o request
    path('filmes/<int:pk>', Detalhesfilmes.as_view(), name="detalhesfilmes"),#pk = primery_key, pega os id do modelo filme
    path('pesquisa/', Pesquisa.as_view(), name='pesquisa'),
    path('login/', auth_views.LoginView.as_view(template_name = 'login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('editarperfil/<int:pk>', Editarperfil.as_view(), name="editarperfil"),
    path('criar/', Criarconta.as_view(), name="criarconta"),
    path('mudarsenha/', auth_views.PasswordChangeView.as_view(template_name='editarperfil.html', success_url="reverse_lazy('filme:homefilmes)"), name='mudarsenha'),
]

hashflix/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('filme.urls', namespace="filme"))#namespace coloca o nome do app_name no ulr do nosso app, e inclui todas as urls do nosso site
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {%block titulo%}
        {%endblock%}
    </title>
    <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
    {%block head%}
        <style>
         
        </style>
    {%endblock%}
</head>
<body class="bg-black text-gray-100 font-primary">
    {%include 'navbar.html'%} <!--inclui o nav e não a pagina-->
    {%block content%}
    {%endblock%}
    <script>
        let nav = document.querySelector('nav');

        window.addEventListener('scroll', () => {
            if (window.scrollY > 100) {
                if (window.scrollY > window.innerHeight) {
                    nav.classList.add('invisible');
                    nav.classList.remove('bg-gray-900')
                    nav.classList.remove('visible');
                } else {
                    nav.classList.add('visible');
                    nav.classList.add('bg-gray-900');
                    nav.classList.remove('invisible');
                }
            } else {
                nav.classList.remove('visible');
                nav.classList.remove('invisible');
            }
        });
        
    </script>
    <script type = "módulo"  src = "https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src = "https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js" ></script>
</body>
</html>

templates/navbar.html
{% load static %}

{% block head %}
    <style>
        nav {
            transition: 0.4s opacity ease, 0.4s transform ease;
            opacity: 1;
            transform: translateY(0);
        }
        .invisible {
            opacity: 0;
            transform: translateY(-100px);
        }
        .visible {
            opacity: 1;
            transform: translateY(0);
        }
        
        
    </style>
{% endblock%}

<nav class="w-full flex justify-between items-center py-3 px-4 fixed z-50">
    <div class="w-6/12">
        <a href="/">
            <img class="w-2/12" src="{% static 'images/hashflix.png' %}">
        </a>
    </div>
        <!--Parmetro user.is_authenticated ele é usado pra saber se p usuario está logado se tiver ele retorna True se não ele retorna False-->
        <div class="w-6/12 flex flex-nowrap justify-end">
            {% if user.is_authenticated %} 
            <div class="mr-2">
                <form method="get" action="{%url 'filme:pesquisa'%}"> <!--Sei que parece estranho mas, o method get no caso, ele tá redirecionando a nossa pesquisa pra nossa página de pesquisa.html e vai passar oq eu digitar dentro o input como parametro na url do meu site-->
                    <input type="text" name="query"class="py-1 px-2 rounded text-black bg-white" placeholder="Pesquisar">
                    <input type="submit" value="">
                </form>
            </div>
            {% endif %}
            {% if user.is_authenticated %} 
            <div class="mr-2">
                <form method="post" action="{% url 'filme:logout' %}">
                    {% csrf_token %}
                    <button class="bg-red-600 text-white py-1 px-3 rounded-md" type="submit">Sair</button><!--A biblioteca do django atualizou por isso tem que fazer com o method post pra funcionar-->
                </form>
            </div>
            {%else%}
            <div class="mr-2">
                <a href="{%url 'filme:login'%}">
                <button class="bg-red-600 text-white py-1 px-3 rounded">
                    Login
                </button>
                </a>
            </div>
            {% endif %}

            {% if user.is_authenticated %} 
                <div class="mr-2">
                    <a href="{%url 'filme:editarperfil' request.user.pk%}"><!--request.user.pk pega o id do usuario que está logado-->
                    <button class="bg-red-600 text-white py-1 px-3 rounded">
                        Editar Perfil
                    </button>
                </a>
                </div>
            {% endif %}
    </div>
</nav>